---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:

- name: build
  image: golang:1.12
  commands:
  - touch .env
  - make release
---
kind: signature
hmac: 78da8c7b5291d185092e148393a6e9680d85c266a09a1671912608226d21d7d8

...
