
# CloudRuntime set the runtime
CloudRuntime = "none"

# GoEnv specifies the type of environment to run.
# Supported values are: 'development' and 'production'. Defaults to "development"
GoEnv = "development"

#Port sets the port on which larissa listens to
Port = "3000"

StorageType = "disk"

LogLevel = "debug"

[Storage]
    [Storage.Disk]
        # RootPath is the Athens Disk Root folder
        # Env override: ATHENS_DISK_STORAGE_ROOT
        RootPath = "data"